export const TOP_FILTER = 'TOP_FILTER';
export const CART_ITEM_REQUEST = 'CART_ITEM_REQUEST';
export const CART_ITEM_SUCCESS = 'CART_ITEM_SUCCESS';
export const CART_ITEM_ERROR = 'CART_ITEM_ERROR';

export const ADD_CART_REQUEST = 'ADD_CART_REQUEST';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_ERROR = 'ADD_CART_ERROR';

export const REMOVE_CART_REQUEST = 'REMOVE_CART_REQUEST';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const REMOVE_CART_ERROR = 'REMOVE_CART_ERROR';

export const CARD_PAYMENT_REQUEST = 'CARD_PAYMENT_REQUEST';
export const CARD_PAYMENT_SUCCESS = 'CARD_PAYMENT_SUCCESS';
export const CARD_PAYMENT_ERROR = 'CARD_PAYMENT_ERROR';

export const LIST_PRODUCT_REQUEST = 'LIST_PRODUCT_REQUEST';
export const LIST_PRODUCT_SUCCESS = 'LIST_PRODUCT_SUCCESS';
export const LIST_PRODUCT_ERROR = 'LIST_PRODUCT_ERROR';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const LIST_CATEGORY_REQUEST = 'LIST_CATEGORY_REQUEST';
export const LIST_CATEGORY_SUCCESS = 'LIST_CATEGORY_SUCCESS';
export const LIST_CATEGORY_ERROR = 'LIST_CATEGORY_ERROR';

export const LIST_PRODUCT_CATEGORY_REQUEST = 'LIST_PRODUCT_CATEGORY_REQUEST';
export const LIST_PRODUCT_CATEGORY_SUCCESS = 'LIST_PRODUCT_CATEGORY_SUCCESS';
export const LIST_PRODUCT_CATEGORY_ERROR = 'LIST_PRODUCT_CATEGORY_ERROR';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const USER_WISHLIST_REQUEST = 'USER_WISHLIST_REQUEST';
export const USER_WISHLIST_SUCCESS = 'USER_WISHLIST_SUCCESS';
export const USER_WISHLIST_ERROR = 'USER_WISHLIST_ERROR';

export const GET_PURCHASED_REQUEST = 'GET_PURCHASED_REQUEST';
export const GET_PURCHASED_SUCCESS = 'GET_PURCHASED_SUCCESS';
export const GET_PURCHASED_ERROR = 'GET_PURCHASED_ERROR';

export const GET_PRODUCT_QTY_MORE_REQ = 'GET_PRODUCT_QTY_MORE_REQ';
export const GET_PRODUCT_QTY_MORE_SUC = 'GET_PRODUCT_QTY_MORE_SUC';
export const GET_PRODUCT_QTY_MORE_EOR = 'GET_PRODUCT_QTY_MORE_EOR';

export const MESSAGE_CLEAR = 'MESSAGE_CLEAR';
